## Laboratorio Nº1 : Manipulación de matrices y Numpy

En un archivo librerias.py, generar la siguiente lista de funciones. Preparar para cada ejercicio un test que verifique que la operación se está realizando correctamente. De la libraría numpy de Python, solo están permitidos utilizar
las funciones que convierten listas a arrays, las que devuelven el tamaño de un array y las funciones que encuentran máximos o mínimos.


In [130]:
import numpy as np

#### Ejercicio 1
Desarrollar una función _esCuadrada(A)_ que devuelva verdadero si la matriz A es cuadrada y Falso en caso contrario.

In [131]:
def esCuadrada(A):
    if (len(A) == len(A[0])) :
        return True
    else:
        return False

M1 = np.array([[1,2,3,4],
               [1,2,3,4],
               [1,2,3,4],
               [1,2,3,4]])

M2 = np.array([[1,2,3,4],
               [1,2,3,4],
               [1,2,3,4]])

M3 = np.array([[1,2,3],
               [1,2,3],
               [1,2,3]])



print(esCuadrada(M1),esCuadrada(M2),esCuadrada(M3))

True False True


#### Ejercicio 2
Desarrollar una función triangSup(A) que devuelva la matriz U correspondiente a la matriz Triangular Superior de A sin su diagonal.

In [132]:

def triangSup(A):
    U = [[val if i<j else 0 for j, val in enumerate(fila)] for i, fila in enumerate(A)]
    return np.array(U)

M3 = np.array([[1,2,3],
               [1,-2,3],
               [1,2,-3]])

M4 = np.array([[1,2,3,4],
               [1,-2,3,5],
               [1,2,-3,7]])
print(triangSup(M3))
print(triangSup(M4))

[[0 2 3]
 [0 0 3]
 [0 0 0]]
[[0 2 3 4]
 [0 0 3 5]
 [0 0 0 7]]


#### Ejercicio3
Desarrollar una función triangInf(A) que devuelva la matriz L correspondiente a la matriz triangular inferior de A sin su diagonal.

In [133]:
def triangInf(A):
    U = [[val if i>j else 0 for j, val in enumerate(fila)] for i, fila in enumerate(A)]
    return np.array(U)

M3 = np.array([[1,2,3],
               [1,-2,3],
               [1,2,-3]])

M4 = np.array([[1,2,3,4],
               [1,-2,3,5],
               [1,2,-3,7]])

print(triangInf(M3))
print(triangInf(M4))

[[0 0 0]
 [1 0 0]
 [1 2 0]]
[[0 0 0 0]
 [1 0 0 0]
 [1 2 0 0]]


#### Ejercicio4 
Desarrollar una función diagonal(A) que devuelva la matriz D correspondiente a la matriz diagonal de A.

In [134]:
def diagonal(A):
    D = [[]]
    if not esCuadrada(A):
        print("La matriz no es cuadrada!")
    else:
        D =[[val if i == j else 0 for j,val in enumerate(fila)]for i,fila in enumerate(A)]

    return np.array(D)

M3 = np.array([[1,2,3],
               [1,-2,3],
               [1,2,-3]])

M4 = np.array([[1,2,3,4],
               [1,-2,3,5],
               [1,2,-3,7]])

print(diagonal(M3))
print(diagonal(M4))
    

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0 -3]]
La matriz no es cuadrada!
[]


#### Ejercicio 5
Desarrollar una función traza(A) que calcule la traza de una matriz cualquiera A

In [135]:
# La traza de una matriz es la suma de los elementos de su diaognal

def traza(A):
    sumaDiag=0
    if not esCuadrada(A):
        print("La matriz no es cuadrada!")
    else:
        matDiag = diagonal(A)
        for i in range(len(matDiag)):
            sumaDiag += matDiag[i][i]
    return sumaDiag

print(traza(M3))
print(traza(M4))

-4
La matriz no es cuadrada!
0


#### Ejercicio 6

Desarrollar una función traspuesta(A) que devuelva la matriz traspuesta A.

In [136]:
def traspuesta(A):
    T = [[fila[i] for fila in A] for i in range(len(A[0]))]
    
    return np.array(T)

print(f"Matriz original:\n {M3}")
print(f"Matriz traspuesta:\n {traspuesta(M3)}")

Matriz original:
 [[ 1  2  3]
 [ 1 -2  3]
 [ 1  2 -3]]
Matriz traspuesta:
 [[ 1  1  1]
 [ 2 -2  2]
 [ 3  3 -3]]


#### Ejercicio 7
Desarrollar una función esSimetrica(A) que devuelve True si la matriz A es simétrica y False en caso contrario.

In [137]:
def esSimetrica(A):
    if len(A)!= len(A[0]):
        return False
    else:
        for i in range(len(A)):
            for j in range(i): # No hace falta mirar TODAS las filas y columnas
                if A[i][j] != A[j][i]:
                    return False
    return True

print(esSimetrica(M3))
print(esSimetrica(M4))

S1 = np.array([[1,2,3],
               [2,1,4],
               [3,4,1]])

print(esSimetrica(S1))

False
False
True


#### Ejercicio 8
Desarrollar una función calcularAx(A,x) que recibe una matriz A de tamaño nxm y un vector x de largo m y devuelve un vector b de largo n resultado de la multiplicación vectorial de la matriz y el vector

In [138]:
# Desarrollar una función calcularAx(A,x) que recibe una matriz A de tamaño nxm y un vector x de largo m y devuelve un vector b de largo n resultado de la multiplicación vectorial de la matriz y el vector

def calcularAx(A,x):
    if len(A[0]) != len(x):
        return None
    else:
        b= [0]*len(A)  # Hago un vector placeholder de longitud "filas(A)"
        for i in range(len(A)):
            for j in range(len(x)):
                b[i] += A[i][j] * x[j]
        return np.array(b)

#np.array(calcularAx(M3, np.array([1,2,3]))).shape

calcularAx(M3, np.array([1,2,3]))

array([14,  6, -4])

#### Ejercicio 9
Desarrollar una función intercambiarFilas(A,i,j) que intercambie las filas i y la j de la matriz A. El intercambio debe ser in-place

In [139]:
M5 = [
    [2.0, 1.0, 1.0],
    [1.0, 2.0, 1.0],
    [1.0, 1.0, 2.0]
]

In [157]:
def intercambiarFilas(A,i,j):
    A[[i,j]] = A[[j,i]]
    return np.array(A)

intercambiarFilas(M4,0,1)

array([[ 1, -2,  3,  5],
       [ 1,  2,  3,  4],
       [ 1,  2, -3,  7]])

#### Ejercicio 10
Desarrollar una función sumar_fila_multiplo(A,i,j,s) que a la fila i le sume la fila j multiplicada por un escalar s. Ésta es una operación clave en la eliminación gaussiana. La operación debe ser in-place 

In [161]:
def sumar_fila_multiplo(A, i, j, s):
    if 0 <= i-1 < len(A) and 0 <= j-1 < len(A):
        fila_origen = list(A[j-1])

        for k in range(len(A[0])):
            A[i-1][k] += s * fila_origen[k]
    return np.array(A)

M6 = [
    [2.0, 1.0, 1.0],
    [1.0, 2.0, 1.0],
    [1.0, 1.0, 2.0]
]

M6 = np.array(sumar_fila_multiplo(M6, 2, 1, -0.5))
sumar_fila_multiplo(M6, 3, 1, -0.5)
sumar_fila_multiplo(M6,3, 2, -(0.5/1.5))
M6

array([[2.        , 1.        , 1.        ],
       [0.        , 1.5       , 0.5       ],
       [0.        , 0.        , 1.33333333]])

In [172]:
intercambiarFilas(M6,0,1)

array([[0.        , 1.5       , 0.5       ],
       [2.        , 1.        , 1.        ],
       [0.        , 0.        , 1.33333333]])

#### Ejercicio 11
Desarrollar una función esDiagonalmenteDominante(A) que devuelva True si una matriz cuadrada A es estrictamente diagonalmente dominante. Eso ocurre si **para cada fila, el valor absoluto del elemento en la diagonal es mayor que la suma de los valores absolutos de los demás elementos en esa fila**

In [202]:
def esDiagonalmenteDominante(A):
    
    if len(A) != len(A[0]):
        return None
    else:
        for i in range(len(A)): # n veces O(n^2)
            suma_sin_diagonal = sum(abs(A[i])) - abs(A[i][i])
            if(abs(A[i][i]) <= suma_sin_diagonal):
                return False
        return True

matrix = np.array([[90,2,3],[3,50,7],[2,2,10]])

esDiagonalmenteDominante(matrix)


True

In [205]:
matrix2 = np.array([
    [5, 1, 1],
    [9, 2, 9],
    [1, 2, 1]
])
esDiagonalmenteDominante(matrix2)



False

#### Ejercicio 12
Desarrollar una función matrizCirculante(v) que genere una matriz circulante a partir de un vector. En una matriz circulante, **la primer fila es igual al vector v y en cada fila se encuentra una permutación cíclica de la fila anterior moviendo los elementos un lugar hacia la derecha**

In [208]:
def matrizCirculante(v):
    tamaño= len(v)
    return np.array([[v[(j-i) % tamaño]for j in range(tamaño)] for i in range(tamaño)])

matrizCirculante([1,2,3])

array([[1, 2, 3],
       [3, 1, 2],
       [2, 3, 1]])

##### Ejercicio 13
Desarrollar una función matrizVandermonde(v) donde v (pertenece a R^n) y se devuelve la matriz de Vandermonde V (perteneciente a R^n*n) cuya fila i-ésima corresponde con la potencia (i-1)-ésima de los elementos de v

In [217]:
# v = (1,2,3)
"""
# V = [[1,1,1],
       [1,2,3],
       [1,4,9]]
"""

def matrizVandermonde(v):
    tamaño= len(v)
    return np.array([[v[j]**i for j in range(tamaño)] for i in range(tamaño)])

matrizVandermonde([1,2,3,4])

array([[ 1,  1,  1,  1],
       [ 1,  2,  3,  4],
       [ 1,  4,  9, 16],
       [ 1,  8, 27, 64]])

#### EJercicio 14

Desarrollar una función numeroAureo(n) que estime el número aureo phi como F_k+1/F_k siendo F_k el k-ésimo numero de la sucesión de Fibonacci. Para ésto formular la sucesión de Fibonacci

F_k+1 = F_k + F_k-1

de forma matricial, usando la semilla F_0 = 0, F_1 =1. Grafique el  valor aproximado de phi en función del número de pasos de la sucesión considerado.

In [218]:
"""
CONSULTAR
"""

'\nCONSULTAR\n'

#### Ejercicio 15
Desarrollar una función matrizFibonacci(n), que genera una matriz A de nxn y cada a_ij = F_i+j, siendo F_k el k-ésimo número de la sucesión de Fibonacci (Considerando F_0 = 0 y F_1 = 1)