## Laboratorio Nº1 : Manipulación de matrices y Numpy

En un archivo librerias.py, generar la siguiente lista de funciones. Preparar para cada ejercicio un test que verifique que la operación se está realizando correctamente. De la libraría numpy de Python, solo están permitidos utilizar
las funciones que convierten listas a arrays, las que devuelven el tamaño de un array y las funciones que encuentran máximos o mínimos.


In [1]:
import numpy as np

#### Ejercicio 1
Desarrollar una función _esCuadrada(A)_ que devuelva verdadero si la matriz A es cuadrada y Falso en caso contrario.

In [13]:
def esCuadrada(A):
    if (len(A) == len(A[0])) :
        return True
    else:
        return False

M1 = np.array([[1,2,3,4],
               [1,2,3,4],
               [1,2,3,4],
               [1,2,3,4]])

M2 = np.array([[1,2,3,4],
               [1,2,3,4],
               [1,2,3,4]])

M3 = np.array([[1,2,3],
               [1,2,3],
               [1,2,3]])



print(esCuadrada(M1),esCuadrada(M2),esCuadrada(M3))

True False True


#### Ejercicio 2
Desarrollar una función triangSup(A) que devuelva la matriz U correspondiente a la matriz Triangular Superior de A sin su diagonal.

In [45]:

def triangSup(A):
    U = [[val if i<j else 0 for j, val in enumerate(fila)] for i, fila in enumerate(A)]
    return np.array(U)

M3 = np.array([[1,2,3],
               [1,-2,3],
               [1,2,-3]])

M4 = np.array([[1,2,3,4],
               [1,-2,3,5],
               [1,2,-3,7]])
print(triangSup(M3))
print(triangSup(M4))

[[0 2 3]
 [0 0 3]
 [0 0 0]]
[[0 2 3 4]
 [0 0 3 5]
 [0 0 0 7]]


#### Ejercicio3
Desarrollar una función triangInf(A) que devuelva la matriz L correspondiente a la matriz triangular inferior de A sin su diagonal.

In [44]:
def triangInf(A):
    U = [[val if i>j else 0 for j, val in enumerate(fila)] for i, fila in enumerate(A)]
    return np.array(U)

M3 = np.array([[1,2,3],
               [1,-2,3],
               [1,2,-3]])

M4 = np.array([[1,2,3,4],
               [1,-2,3,5],
               [1,2,-3,7]])

print(triangInf(M3))
print(triangInf(M4))

[[0 0 0]
 [1 0 0]
 [1 2 0]]
[[0 0 0 0]
 [1 0 0 0]
 [1 2 0 0]]


#### Ejercicio4 
Desarrollar una función diagonal(A) que devuelva la matriz D correspondiente a la matriz diagonal de A.

In [57]:
def diagonal(A):
    D = [[]]
    if not esCuadrada(A):
        print("La matriz no es cuadrada!")
    else:
        D =[[val if i == j else 0 for j,val in enumerate(fila)]for i,fila in enumerate(A)]

    return np.array(D)

M3 = np.array([[1,2,3],
               [1,-2,3],
               [1,2,-3]])

M4 = np.array([[1,2,3,4],
               [1,-2,3,5],
               [1,2,-3,7]])

print(diagonal(M3))
print(diagonal(M4))
    

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0 -3]]
La matriz no es cuadrada!
[]


#### Ejercicio 5
Desarrollar una función traza(A) que calcule la traza de una matriz cualquiera A

In [61]:
# La traza de una matriz es la suma de los elementos de su diaognal

def traza(A):
    sumaDiag=0
    if not esCuadrada(A):
        print("La matriz no es cuadrada!")
    else:
        matDiag = diagonal(A)
        for i in range(len(matDiag)):
            sumaDiag += matDiag[i][i]
    return sumaDiag

print(traza(M3))
print(traza(M4))

-4
La matriz no es cuadrada!
0


#### Ejercicio 6

Desarrollar una función traspuesta(A) que devuelva la matriz traspuesta A.

In [75]:
def traspuesta(A):
    T = [[fila[i] for fila in A] for i in range(len(A[0]))]
    
    return np.array(T)

print(f"Matriz original:\n {M3}")
print(f"Matriz traspuesta:\n {traspuesta(M3)}")

Matriz original:
 [[ 1  2  3]
 [ 1 -2  3]
 [ 1  2 -3]]
Matriz traspuesta:
 [[ 1  1  1]
 [ 2 -2  2]
 [ 3  3 -3]]


#### Ejercicio 7
Desarrollar una función esSimetrica(A) que devuelve True si la matriz A es simétrica y False en caso contrario.

In [86]:
def esSimetrica(A):
    if len(A)!= len(A[0]):
        return False
    else:
        for i in range(len(A)):
            for j in range(i): # No hace falta mirar TODAS las filas y columnas
                if A[i][j] != A[j][i]:
                    return False
    return True

print(esSimetrica(M3))
print(esSimetrica(M4))

S1 = np.array([[1,2,3],
               [2,1,4],
               [3,4,1]])

print(esSimetrica(S1))

False
False
True


#### Ejercicio 8
Desarrollar una función calcularAx(A,x) que recibe una matriz A de tamaño nxm y un vector x de largo m y devuelve un vector b de largo n resultado de la multiplicación vectorial de la matriz y el vector

In [ ]:
# Desarrollar una función calcularAx(A,x) que recibe una matriz A de tamaño nxm y un vector x de largo m y devuelve un vector b de largo n resultado de la multiplicación vectorial de la matriz y el vector

def calcularAx(A,x):
    if len(A[0]) != len(x):
        return None
    else:
        b= [0]*len(A)  # Hago un vector placeholder de longitud "filas(A)"
        for i in range(len(A)):
            for j in range(len(x)):
                b[i] += A[i][j] * x[j]
        return np.array(b)

#np.array(calcularAx(M3, np.array([1,2,3]))).shape

calcularAx(M3, np.array([1,2,3]))

array([14,  6, -4])

#### Ejercicio 9
Desarrollar una función sumar_fila_multiplo(A,i,j,s) que a la fila i le sume la fila j multiplicada por un escalar s. Ésta es una operación clave en la eliminación gaussiana. La operación debe ser in-place 

In [137]:
def sumar_fila_multiplo(A, i, j, s):
    if 0 <= i-1 < len(A) and 0 <= j-1 < len(A):
        fila_origen = list(A[j-1])

        for k in range(len(A[0])):
            A[i-1][k] += s * fila_origen[k]
    return A

M5 = [
    [2.0, 1.0, 1.0],
    [1.0, 2.0, 1.0],
    [1.0, 1.0, 2.0]
]

M5 = np.array(sumar_fila_multiplo(M5, 2, 1, -0.5))
sumar_fila_multiplo(M5, 3, 1, -0.5)
sumar_fila_multiplo(M5,3, 2, -(0.5/1.5))
print(M5)

[[2.         1.         1.        ]
 [0.         1.5        0.5       ]
 [0.         0.         1.33333333]]
